feat: Initial Implementation
nitrictech/grpc-error-status pull request #1
Opened 2023-10-19 01:23 UTC by tjholm

2023-10-19 03:05 UTC, davemooreuws requested changes
fix up the license and potentially add the license comments for Nitric

2023-10-19 23:44 UTC, davemooreuws requested changes, later dismissed

2023-10-19 23:44 UTC, davemooreuws commented on package.json
> +  "license": "MIT",
```suggestion
  "license": "Apache-2.0",
```

2023-10-19 23:53 UTC, jyecusch commented on src/index.ts
> +                // ignore not found we're only searching for a specific type
maybe add `continue` here to make that explicit?

2023-10-19 23:55 UTC, jyecusch approved these changes

2023-10-20 00:02 UTC, davemooreuws approved these changes

2023-10-20 00:02 UTC, merged